---
common_packages:
  - vim
  - firewalld
  - chrony
  - policycoreutils-python-utils
  - setools-console
  - bind-utils
  - tcpdump
  - net-tools
  - lvm2
  - tar
  - rsync

timezone: America/New_York

sysctl_params:
  net.ipv4.ip_forward: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.icmp_echo_ignore_broadcasts: 1
  net.ipv4.conf.all.log_martians: 1

selinux_state: enforcing
