---
galaxy_info:
  author: Justin
  description: Firewalld configuration role for managing firewall services and zones on RHEL/AlmaLinux systems
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - firewall
    - firewalld
    - security
    - networking
    - rhel
    - almalinux

dependencies: []
